name: CI

on:
  - pull_request
  - workflow_dispatch

jobs:
  validate-json-schemas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install avj
        run: npm install --no-save ajv-cli@5.0.0
      - name: validate all schema files
        run: find ./schemas -name "*.json" | xargs -n 1 -I {} npx ajv-cli compile -s {} --strict=false
  test-against-sample-dbt-files:
    strategy:
      matrix:
        dbt-version: ["1.5", "1.6"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install avj
        run: npm install --no-save ajv-cli@5.0.0
      - name: Validate dbt_project.yml sample files for dbt version ${{ matrix.dbt-version }}
        run: |
          npx ajv-cli test -s schemas/${{ matrix.dbt-version }}/dbt_project-${{ matrix.dbt-version }}.json -d tests/${{ matrix.dbt-version }}/valid/dbt_project.yml --valid
          npx ajv-cli test -s schemas/${{ matrix.dbt-version }}/dbt_project-${{ matrix.dbt-version }}.json -d tests/${{ matrix.dbt-version }}/invalid/dbt_project.yml --invalid
      
      - name: Validate resource yml sample files for dbt version ${{ matrix.dbt-version }}
        run: |
          npx ajv-cli test -s schemas/${{ matrix.dbt-version }}/dbt_yml_files-${{ matrix.dbt-version }}.json -d tests/${{ matrix.dbt-version }}/valid/schema.yml --valid
          npx ajv-cli test -s schemas/${{ matrix.dbt-version }}/dbt_yml_files-${{ matrix.dbt-version }}.json -d tests/${{ matrix.dbt-version }}/invalid/schema.yml --invalid

      - name: Validate packages.yml sample files for dbt version ${{ matrix.dbt-version }}
        run: |
          npx ajv-cli test -s schemas/${{ matrix.dbt-version }}/packages-${{ matrix.dbt-version }}.json -d tests/${{ matrix.dbt-version }}/valid/packages.yml --valid
          npx ajv-cli test -s schemas/${{ matrix.dbt-version }}/packages-${{ matrix.dbt-version }}.json -d tests/${{ matrix.dbt-version }}/invalid/packages.yml --invalid
      
      - name: Validate selectors.yml sample files for dbt version 1.5
        run: |
          npx ajv-cli test -s schemas/${{ matrix.dbt-version }}/selectors-${{ matrix.dbt-version }}.json -d tests/${{ matrix.dbt-version }}/valid/selectors.yml --valid
          npx ajv-cli test -s schemas/${{ matrix.dbt-version }}/selectors-${{ matrix.dbt-version }}.json -d tests/${{ matrix.dbt-version }}/invalid/selectors.yml --invalid

      - name: Validate dependencies.yml sample files for dbt version 1.6
        run: |
          npx ajv-cli test -s schemas/dependencies-1.6.json -d tests/1.6/valid/dependencies.yml --valid
          npx ajv-cli test -s schemas/dependencies-1.6.json -d tests/1.6/invalid/dependencies.yml --invalid

  validate_plusless_properties:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: install avj
        run: |
          python -m pip install --upgrade pip
          pip install jsondiff
      - name: Validate dbt_project.json has equivalent properties with and without pluses
        run: |
          python tests/validate_plusless_properties.py
